# todo description
# requires render-sec-scanners-config.sh
name: Lint code (reusable)

on:
  workflow_call:
    secrets:
      BOT_PAT:
        required: true

jobs:
  bump:
    name: bump sec-scanners-config.yaml
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Render sec-scanners-config.sh
        shell: bash
        # Where ever you use this workflow, the script hack/scripts/render-sec-scanners-config.sh must exist.
        run: ./hack/scripts/render-sec-scanners-config.sh

      - name: Check for Changes
        id: skip_check
        run: |
          if [ -z $(git status --porcelain) ]; then
            echo "No changes found. No need to create a PR"
          else
            echo "Changes found. Creating a PR and waiting for it to be merged."
            echo "create_pr=true" >> $GIHUB_ENV
          fi

      - name: Set Up Git
        if: ${{ env.create_pr == 'true' }}
        env:
          GH_TOKEN: ${{ secrets.BOT_PAT }}
        run: |
          ghusername=$(curl -H "Authorization: token {GH_TOKEN}" https://api.github.com/user)
          git config user.name "${ghusername}"

          ghmailaddress=$(curl -H "Authorization: token {GH_TOKEN}" https://api.github.com/email)
          git config user.email "${ghmailaddress}"

      - name: Create a pull request
        if: ${{ env.create_pr == 'true' }}
        env:
          REPO: ${{ github.repository }}
          GH_TOKEN: ${{ secrets.BOT_PAT }}
        shell: bash
        run: |
          echo "Uncommitted changes found. Committing changes..."


          CURRENT_BRANCH="$(git rev-parse --abbrev-ref HEAD)"
          echo "${CURRENT_BRANCH}"
          PR_DATE="$(date '+%Y-%m-%d-%H-%M-%S')"
          echo "${PR_DATE}"
          BRANCH_NAME="sec-scanners-bump-${CURRENT_BRANCH}-${PR_DATE}"
          echo "${BRANCH_NAME}" 
          git checkout -b "${BRANCH_NAME}"

          git add sec-scanners-config.yaml
          git commit -m "auto-bump sec-scanners-config: ${PR_DATE}"
                   
          git remote set-url origin "https://x-access-token:${GH_TOKEN}@github.com/${REPO}.git"
          git push origin "$BRANCH_NAME"

          BODY="This is an auto-generated PR to bump the sec-scanners-config.yml on ${REPO}."
          gh pr create --base "${CURRENT_BRANCH}" --head "${BRANCH_NAME}" --title "Bump sec-scanners-config on ${CURRENT_BRANCH}" --body "${BODY}"
