# todo description
# requires render-sec-scanners-config.sh
name: Lint code (reusable)

on:
  workflow_call:
    secrets:
      BOT_PAT:
        required: true

jobs:
  bump:
    name: Bump sec-scanners-config.yaml
    runs-on: ubuntu-latest
    env:
      REPO: ${{ github.repository }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Render sec-scanners-config.yaml
        shell: bash
        # Where ever you use this workflow, the script hack/scripts/render-sec-scanners-config.sh must exist.
        run: ./hack/scripts/render-sec-scanners-config.sh

      # Check if there are changes so we can determin if all following steps can be skipped.
      - name: Check For Changes
        shell: bash
        run: |
          if [ -z "$(git status --porcelain)" ]; then 
            echo "No changes found. No need to create a PR" 
          else 
            echo "Changes found. Creating a PR and waiting for it to be merged." 
            echo "create_pr=true" >> $GITHUB_ENV 
          fi

      - name: Set Up Git
        if: ${{ env.create_pr == 'true' }}
        env:
          GH_TOKEN: ${{ secrets.BOT_PAT }}
        shell: bash
        run: |
          # set git username 
          ghusername=$(curl -H "Authorization: token ${GH_TOKEN}" https://api.github.com/user)
          git config user.name "${ghusername}"
          # set git mail address
          ghmailaddress=$(curl -H "Authorization: token ${GH_TOKEN}" https://api.github.com/email)
          git config user.email "${ghmailaddress}"
          # set remote url
          git remote set-url origin "https://x-access-token:${GH_TOKEN}@github.com/${REPO}.git"

      - name: Set All Variables
        if: ${{ env.create_pr == 'true' }}
        shell: bash
        run: |
          CURRENT_BRANCH="$(git rev-parse --abbrev-ref HEAD)"
          echo "current branch: ${CURRENT_BRANCH}"
          echo "CURRENT_BRANCH=${CURRENT_BRANCH}" >> $GITHUB_ENV

          PR_DATE="$(date '+%Y-%m-%d-%H-%M-%S')"
          echo "pr date: ${PR_DATE}"
          echo "PR_DATE=${PR_DATE}" >> $GITHUB_ENV

          BRANCH_NAME="sec-scanners-bump-${CURRENT_BRANCH}-${PR_DATE}"
          echo "name of the new branch: ${BRANCH_NAME}"
          echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_ENV

      - name: Create a Pull Request
        if: ${{ env.create_pr == 'true' }}
        env:
          CURRENT_BRANCH: ${{ env.CURRENT_BRANCH }}
          PR_DATE: ${{ env.PR_DATE }}
          BRANCH_NAME: ${{ env.BRANCH_NAME }}
        shell: bash
        run: |
          git checkout -b "${BRANCH_NAME}"

          git add sec-scanners-config.yaml
          git commit -m "auto-bump sec-scanners-config: ${PR_DATE}"
                   
          git push origin "$BRANCH_NAME"

          BODY="This is an auto-generated PR to bump the sec-scanners-config.yml on ${REPO}."
          gh pr create --base "${CURRENT_BRANCH}" --head "${BRANCH_NAME}" --title "Bump sec-scanners-config on ${CURRENT_BRANCH}" --body "${BODY}"
