name: Render and upload manifests

on:
  workflow_dispatch:
    inputs:
      VERSION:
        required: true
        type: string
        description: The semantic version number.
      CR_FILE_NAME:
        type: string
        required: true
        description: The file name of the CR.
      CRD_FILE_NAME:
        type: string
        required: true
        description: The file name of the CRD.
    secrets:
      BOT_PAT:
        required: true
        description: The github personal access token of your bot.

jobs:
  render-and-upload-manifests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Up Git
        if: ${{ env.create_pr == 'true' }}
        env:
          BOT_PAT: ${{ secrets.BOT_PAT }}
          REPO: ${{ github.repository }}
        shell: bash
        run: |
          # set git username 
          ghusername=$(curl -s -H "Authorization: token ${BOT_PAT}" https://api.github.com/user)
          git config user.name "${ghusername}"
          # set git mail address
          ghmailaddress=$(curl -s -H "Authorization: token ${BOT_PAT}" https://api.github.com/email)
          git config user.email "${ghmailaddress}"
          # set remote url
          git remote set-url origin "https://x-access-token:${BOT_PAT}@github.com/${REPO}.git"

      - name: Render CRD
        env:
          VERSION: ${{ inputs.VERSION }}
          CRD_FILE_NAME: ${{ inputs.CRD_FILE_NAME }}
        shell: bash
        run: ./hack/scripts/render_crd.sh "${VERSION}" "${CRD_FILE_NAME}"

      - name: Print out CR file
        shell: bash
        run: cat "${CR_FILE_NAME}"

      - name: Print out CRD file
        shell: bash
        run: cat "${CRD_FILE_NAME}"

      - name: Upload manifests
        env:
          VERSION: ${{ inputs.VERSION }}
        shell: bash
        run: |
          gh release upload "${VERSION}"\
          "${CRD_FILE_NAME}"\
          "${CR_FILE_NAME}"
