name: Unit Test (reusable)

on:
  workflow_call:

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21" # todo consider using the line underneath.
          # go-version-file: 'go.mod' # This uses the Go version defined in the mod file, in contrast to setting a defined version of go, here.
          cache: false # todo consider activating this.

      - name: Sync Go dependencies
        run: |
          go mod tidy # todo consider removing; there should be not requirement to tidy the dependencies at this place
          go mod vendor

      - name: Run tests
        run: |
          make test
